#!/bin/bash
#PBS parameters...

id_run=1
WORKING_DIRECTORY=					#path to working directory
PYTHON_SCRIPT=${WORKING_DIRECTORY}/src/vcf_sex.py	#path to python script
PYTHON_ENV=${WORKING_DIRECTORY}/python_env		#path to conda environnement
COPY_VCF_FILE=${WORKING_DIRECTORY}/input/sex_det_snp_DP10_maf0.1_miss0.9.recode_biallelic_noComplex.vcf_copie	#path to input vcf file to process
BASENAME_VCF=${COPY_VCF_FILE##*/}			
FINAL_OUTPUT=${WORKING_DIRECTORY}/results/${BASENAME_VCF}.chi2_${id_run}	#output file name
LOG=${WORKING_DIRECTORY}/log/${BASENAME_VCF}.chi2_${id_run}.log		#log file name


#Chargement de conda
export PATH=$PATH:/appli/anaconda/2.7/bin

source activate ${PYTHON_ENV}

cd ${WORKING_DIRECTORY} 

python ${PYTHON_SCRIPT} ${COPY_VCF_FILE} -o ${FINAL_OUTPUT} >& ${LOG} 2>&1
